apiVersion: v1
kind: ConfigMap
metadata:
    name: symfony-api-config
    namespace: the-tip-top-api
data:
    APP_ENV: "prod"
    APP_DEBUG: "0"

    # Si sous-domaine sp√©cifique :
    SESSION_COOKIE_DOMAIN: ".the-tip-top.jonathanlore.fr"
    SESSION_COOKIE_SECURE: "true"  # HTTPS uniquement
    SESSION_COOKIE_SAMESITE: "lax"

    # CORS : autorise le frontend
    CORS_ALLOW_ORIGIN: "^https://(www\\.)?the-tip-top\\.jonathanlore\\.fr$"

    # URLs publiques
    FRONTEND_URL: "https://the-tip-top.jonathanlore.fr"
    API_URL: "https://api.the-tip-top.jonathanlore.fr"
