apiVersion: apps/v1
kind: Deployment
metadata:
    name: symfony-api
    namespace: the-tip-top-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: symfony-api
    template:
        metadata:
            labels:
                app: symfony-api
        spec:

            initContainers:
                - name: fix-jwt-permissions
                  image: busybox
                  command:
                      - sh
                      - -c
                      - |
                          echo "[Init] Fixing JWT permissions..."
                          chmod 640 /var/www/html/config/jwt/private.pem
                          chmod 644 /var/www/html/config/jwt/public.pem
                          chown -R 33:33 /var/www/html/config/jwt
                  volumeMounts:
                      - name: jwt-keys
                        mountPath: /var/www/html/config/jwt

            containers:
                - name: app
                  image: joanisky/the-tip-top-api:latest
                  ports:
                      - containerPort: 80
                  envFrom:
                      - secretRef:
                            name: symfony-env
                  volumeMounts:
                      - name: jwt-keys
                        mountPath: /var/www/html/config/jwt
                        readOnly: false
                  resources:
                      requests:
                          memory: "64Mi"
                          cpu: "50m"
                      limits:
                          memory: "128Mi"
                          cpu: "100m"

            volumes:
                - name: jwt-keys
                  secret:
                      secretName: jwt-keys   # ✔️ le secret créé par Jenkins
