apiVersion: apps/v1
kind: Deployment
metadata:
    name: symfony-api
    namespace: the-tip-top-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: symfony-api
    template:
        metadata:
            labels:
                app: symfony-api
        spec:
            containers:
                - name: app
                  image: joanisky/the-tip-top-api:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                        name: http

                  envFrom:
                      # Variables depuis ConfigMap (non sensibles)
                      - configMapRef:
                            name: symfony-api-config
                      # Variables depuis Secret (sensibles)
                      - secretRef:
                            name: symfony-env
                  volumeMounts:
                      - name: jwt-keys
                        mountPath: /var/www/html/config/jwt
                        readOnly: true
                  resources:
                      requests:
                          memory: "128Mi"
                          cpu: "100m"
                      limits:
                          memory: "256Mi"
                          cpu: "200m"

                  livenessProbe:
                      httpGet:
                          path: /api
                          port: 80
                      initialDelaySeconds: 30
                      periodSeconds: 20
                      timeoutSeconds: 5
                      failureThreshold: 3

                  readinessProbe:
                      httpGet:
                          path: /api
                          port: 80
                      initialDelaySeconds: 10
                      periodSeconds: 10
                      timeoutSeconds: 3
                      failureThreshold: 3

            volumes:
                - name: jwt-keys
                  secret:
                      secretName: jwt-keys   # secret créé par Jenkins
