apiVersion: apps/v1
kind: Deployment
metadata:
    name: symfony-api
    namespace: the-tip-top-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: symfony-api
    template:
        metadata:
            labels:
                app: symfony-api
        spec:
            containers:
                - name: app
                  image: joanisky/the-tip-top-api:latest
                  ports:
                      - containerPort: 80
                  envFrom:
                      - secretRef:
                            name: symfony-env
                  volumeMounts:
                      - name: jwt-private
                        mountPath: /var/www/html/config/jwt/private.pem
                        subPath: private.pem
                        readOnly: true
                      - name: jwt-public
                        mountPath: /var/www/html/config/jwt/public.pem
                        subPath: public.pem
                        readOnly: true
                  resources:
                      requests:
                          memory: "64Mi"
                          cpu: "50m"
                      limits:
                          memory: "128Mi"
                          cpu: "100m"
            volumes:
                - name: jwt-private
                  secret:
                      secretName: jwt-private-key
                - name: jwt-public
                  secret:
                      secretName: jwt-public-key
