apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: phpmyadmin-ingress
    namespace: the-tip-top-api
    annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
        traefik.ingress.kubernetes.io/router.middlewares: the-tip-top-api-pma-https@kubernetescrd

spec:
    tls:
        - hosts:
              - pma.the-tip-top.jonathanlore.fr
          secretName: pma-the-tip-top-tls
    rules:
        - host: pma.the-tip-top.jonathanlore.fr
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: phpmyadmin
                            port:
                                number: 80
