apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: pma-headers
    namespace: the-tip-top-api
spec:
    headers:
        customResponseHeaders:
            Set-Cookie: "Path=/; Secure; HttpOnly; SameSite=None"
