apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: pma-headers
    namespace: the-tip-top-api
spec:
    headers:
        customRequestHeaders:
            # Injecte l'en-tÃªte indiquant que le protocole client est HTTPS
            X-Forwarded-Proto: "https"
