apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: pma-https
    namespace: the-tip-top-api
spec:
    headers:
        customRequestHeaders:
            X-Forwarded-Proto: https
